version: "3"

services:
  postgres:
    image: postgres:14.2
    command: "postgres -c 'max_connections=100' -c 'client_min_messages=warning'"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "company"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrations:
    build:
      context: .
      dockerfile: migrations.Dockerfile
    entrypoint: ["alembic"]
    command: ["upgrade", "head"]
    depends_on:
      - postgres

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - migrations

volumes:
  pgdata: